### ISSUE TITLE
dns_sd.h is missed. Compile of DNSSD/Bonjour fails

### ISSUE THREAD

**Issue by petersmar** [pocoproject/poco-dnssd#1]
To compile the DNSSD library I included the poco-dnssd-master folder into the poco-1.7.4-all folder and renamed it to DNSSD. Additionally I added "DNSSD" to the component file and startet the windows-build. The DNSSD libraries were build without any errors but the DNSSD/Bonjour failed, because the file dns_sd.h is missed.
Where to get the dns_sd.h file?

This is the first error line:
1>E:\poco-1.7.4-all\DNSSD\Bonjour\include\Poco/DNSSD/Bonjour/EventLoop.h(30): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory [E:\poco-1.7.4-all\DNSSD\Bonjour\Bonjour_vs100.vcxproj]

**Comment by obiltschnig** [comment]
As stated in the [README.md](https://github.com/pocoproject/poco-dnssd/blob/master/README.md), you'll need to install the [Bonjour SDK](https://developer.apple.com/bonjour/), which has the dns_sd.h header, on Windows, in order to build the DNSSD/Bonjour library.

**Comment by petersmar** [comment]
Thanks for the hint. I just had installed the Bonjour driver but not the SDK.
