### ISSUE TITLE
Build Problem while building Default

### ISSUE THREAD

**Issue by abhisheksafui** [pocoproject/poco-dnssd#8]
I am getting following error while doing 
make -s -j8 Default: 

make -s -j8 -C Default
** Creating dependency info for src/AvahiBrowserImpl.cpp
** Creating dependency info for src/AvahiResponderImpl.cpp
In file included from include/Poco/DNSSD/Avahi/AvahiResponderImpl.h:23:0,
                 from src/AvahiResponderImpl.cpp:17:
include/Poco/DNSSD/Avahi/Avahi.h:25:30: fatal error: Poco/DNSSD/DNSSD.h: No such file or directory
In file included from include/Poco/DNSSD/Avahi/AvahiBrowserImpl.h:23:0,
                 from src/AvahiBrowserImpl.cpp:17:
include/Poco/DNSSD/Avahi/Avahi.h:25:30: fatal error: Poco/DNSSD/DNSSD.h: No such file or directory
compilation terminated.
compilation terminated.
** Compiling src/AvahiBrowserImpl.cpp (debug, shared)
** Compiling src/AvahiResponderImpl.cpp (debug, shared)
** Compiling src/AvahiBrowserImpl.cpp (release, shared)
** Compiling src/AvahiResponderImpl.cpp (release, shared)
In file included from include/Poco/DNSSD/Avahi/AvahiBrowserImpl.h:23:0,
                 from src/AvahiBrowserImpl.cpp:17:
include/Poco/DNSSD/Avahi/Avahi.h:25:30: fatal error: Poco/DNSSD/DNSSD.h: No such file or directory
compilation terminated.
In file included from include/Poco/DNSSD/Avahi/AvahiResponderImpl.h:23:0,
                 from src/AvahiResponderImpl.cpp:17:
include/Poco/DNSSD/Avahi/Avahi.h:25:30: fatal error: Poco/DNSSD/DNSSD.h: No such file or directory
In file included from include/Poco/DNSSD/Avahi/AvahiResponderImpl.h:23:0,
                 from src/AvahiResponderImpl.cpp:17:
include/Poco/DNSSD/Avahi/Avahi.h:25:30: fatal error: Poco/DNSSD/DNSSD.h: No such file or directory
compilation terminated.
compilation terminated.
/home/abhi/Downloads/poco/build/rules/compile:51: recipe for target '/home/abhi/Downloads/poco/DNSSD/Avahi/obj/Linux/x86_64/debug_shared/AvahiBrowserImpl.o' failed
make[1]: *** [/home/abhi/Downloads/poco/DNSSD/Avahi/obj/Linux/x86_64/debug_shared/AvahiBrowserImpl.o] Error 1
make[1]: *** Waiting for unfinished jobs....
/home/abhi/Downloads/poco/build/rules/compile:55: recipe for target '/home/abhi/Downloads/poco/DNSSD/Avahi/obj/Linux/x86_64/release_shared/AvahiResponderImpl.o' failed
make[1]: *** [/home/abhi/Downloads/poco/DNSSD/Avahi/obj/Linux/x86_64/release_shared/AvahiResponderImpl.o] Error 1
/home/abhi/Downloads/poco/build/rules/compile:51: recipe for target '/home/abhi/Downloads/poco/DNSSD/Avahi/obj/Linux/x86_64/debug_shared/AvahiResponderImpl.o' failed
make[1]: *** [/home/abhi/Downloads/poco/DNSSD/Avahi/obj/Linux/x86_64/debug_shared/AvahiResponderImpl.o] Error 1
In file included from include/Poco/DNSSD/Avahi/AvahiBrowserImpl.h:23:0,
                 from src/AvahiBrowserImpl.cpp:17:
include/Poco/DNSSD/Avahi/Avahi.h:25:30: fatal error: Poco/DNSSD/DNSSD.h: No such file or directory
compilation terminated.
/home/abhi/Downloads/poco/build/rules/compile:55: recipe for target '/home/abhi/Downloads/poco/DNSSD/Avahi/obj/Linux/x86_64/release_shared/AvahiBrowserImpl.o' failed
make[1]: *** [/home/abhi/Downloads/poco/DNSSD/Avahi/obj/Linux/x86_64/release_shared/AvahiBrowserImpl.o] Error 1
Makefile:21: recipe for target 'projects' failed
make: *** [projects] Error 2

**Comment by soroshsabz** [comment]
ITNOA

Hi,

Did you test https://github.com/soroshsabz/poco-dnssd?

**Comment by abhisheksafui** [comment]
yes same issue. 
First I cloned into poco. 
Then cloned DNSSD inside poco. 
Then followed linux build instructions. 
make -s -j8 completed. 
but Default causing problems.

**Comment by obiltschnig** [comment]
edit the `components` file and add:
```
DNSSD
DNSSD/Bonjour
DNSSD/Avahi
```

**Comment by soroshsabz** [comment]
ITNOA


Did you apply patch as described in link?

Sent from my Windows 10 phone

**Comment by abhisheksafui** [comment]
Adding to components solved the problem.
