### ISSUE TITLE
Please help cross compile DNSSD

### ISSUE THREAD

**Issue by abhisheksafui** [pocoproject/poco-dnssd#9]
I am trying to cross compile for arm. I have successfully compiled poco for arm using:

./configure --config=ARM-Linux --no-samples  --no-tests --include-path=....... --library-path=......  --prefix=....... --everything
I have edited ARM-linux as required. 

Following the steps mentioned in README DNSSD compiles but for x86. How to compile DNSSD just like any other component like JSON. They have the same makefile, How to make POCO_BASE pickup DNSSD like others. I tried adding to components like this: 

CppUnit
CppUnit/WinTestRunner
Foundation
Encodings
XML
JSON
Util
Net
DNSSD
DNSSD/Avahi
DNSSD/Default

That did not pick up DNSSD. 

Please help

**Comment by abhisheksafui** [comment]
After exporting POCO_CONFIG=ARM-linux besides the steps in README, its taking up cross compiler now. But is there any way to compile and install from poco base?

**Comment by obiltschnig** [comment]
You'll need to either edit the Poco top-level Makefile to include DNSSD, or set `POCO_BASE` accordingly, then `cd` into the DNSSD directory and run make with `POCO_CONFIG` set to your target build configuration.
Example:
```
export POCO_BASE=/path/to/poco
cd /path/to/DNSSD
make POCO_CONFIG=ARM-Linux
cd Avahi
make POCO_CONFIG=ARM-Linux
```
